name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello GitHub actions!!"
      - name: Print Godbye
        run: echo "Bye!"
