name: 'Cached dependencies'
description: 'Get the dependencies via npm & cache if not present then install'
inputs:
  caching:
    description: 'Whether to cache dpendencies or not'
    required: false
    default: 'true'
  project-path:
    description: 'Add project path for which caching is to be done'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate project path
      id: validate
      run: |
        if [ -d "${{ inputs.project-path }}" ]; then
          echo "project-path-validity=true" >> $GITHUB_OUTPUT
        else
          echo "project-path-validity=false" >> $GITHUB_OUTPUT
          echo "Error: Provided project-path '${{ inputs.project-path }}' is not valid or does not exist."
          echo "Your Present working directory is (PWD): $(pwd)"
          exit 1
        fi
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == 'true' 
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.project-path }}/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.project-path }}
