name: Test 02-starting-project
on: push
jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Change directory
        run: cd 01-basics/02-starting-project
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: 01-basics/02-starting-project
      - name: Run tests
        run: npm test
        working-directory: 01-basics/02-starting-project