name: Reusable deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string 
#   push:
#     branches:
#       - main
env:
  PROJECT_DIR: 05-exec-flow/05-exec-flow-project
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output files Information
        run: |
          ls
          echo "Deploying...."
        

     
