name: Custom Action starting Project
on:
  push:
    branches:
      - main
  workflow_dispatch: 
env:
  PROJECT_DIR: 07-custom-actions/07-custom-starting-project
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        id: cached-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
          project-path: ${{env.PROJECT_DIR}}
      - name: Output project path
        run: echo "Project path => ${{steps.cached-deps.outputs.project-path}}"
      - name: Lint code
        run: npm run lint
        working-directory: ${{ env.PROJECT_DIR }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          project-path: ${{env.PROJECT_DIR}}
      - name: Test code
        id: run-tests
        run: npm run test
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ env.PROJECT_DIR}}/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          project-path: ${{env.PROJECT_DIR}}
      - name: Build website
        run: npm run build
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ${{ env.PROJECT_DIR }}/dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."