name: Cron job keep active Lightning studio
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
env:
  LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
  LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
  LIGHTNING_USER: ${{ secrets.LIGHTNING_USER }}
  LIGHTNING_TEAMSPACE: ${{ secrets.LIGHTNING_TEAMSPACE }}
  LIGHTNING_STUDIO_NAME: ${{ secrets.LIGHTNING_STUDIO_NAME }}
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          
      - name: Upgrade pip & install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
   
      - name: Run python script
        run: python lightning_studio_active.py
